#
# Created by Pretti_
#

#
# Permissions
#
# prtprotect.command = Permission to run /protect
# prtprotect.command.reload = Permission to run /protect reload


#
# Block interaction options
# Use [] to disable checks
#
interact-entity-blocked:
- 'BOAT'

interact-block-blocked:
- 'HOPPER'

interact-item-blocked:
- 'ENDER_PEARL'

craft-blocked:
- 'ARMOR_STAND'
- 'TRIPWIRE_HOOK'
- 'PISTON_STICKY_BASE'
- 'PISTON_BASE'
- 'REDSTONE_TORCH_ON'
- 'DROPPER'
- 'DISPENSER'
- 'NOTE_BLOCK'
- 'TNT'
- 'DIODE'
- 'REDSTONE_COMPARATOR'
- 'DAYLIGHT_DETECTOR'
- 'MINECART'
- 'BOAT'
- 'BOOK_AND_QUILL'
- 'JUKEBOX'
- 'HOPPER'
- 'BEACON'
- 'BED'