#
# Created by Pretti_
#

#
# Permissions
#
# prtprotect.command = Permission to run /protect
# prtprotect.command.reload = Permission to run /protect reload
#
# prtprotect.bypass = Permission to bypass checks

#
# Materials
# 1.8 = https://helpch.at/docs/1.8/index.html?org/bukkit/Material.html
# latest = https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

#
# Block interaction options
# Use [] to disable checks
#
interact-entity-blocked:
- 'VILLAGER'
#- 'BOAT'
#- 'OAK_BOAT'

interact-block-blocked:
- 'HOPPER'

interact-item-blocked:
- 'ENDER_PEARL'

# Block player crafting (1.8+)
# Block auto-crafting (spigot 1.21+)
craft-blocked:
- 'ARMOR_STAND'
- 'TRIPWIRE_HOOK'
- 'DROPPER'
- 'DISPENSER'
- 'NOTE_BLOCK'
- 'TNT'
- 'DAYLIGHT_DETECTOR'
- 'MINECART'
- 'JUKEBOX'
- 'HOPPER'
- 'BEACON'